// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbeVl5JtWs3xNAKN5JOKHe-lGbThjL3RA',
    appId: '1:330302895133:web:08d20607649fbdfc65c2f4',
    messagingSenderId: '330302895133',
    projectId: 'canteenapp-f839a',
    authDomain: 'canteenapp-f839a.firebaseapp.com',
    storageBucket: 'canteenapp-f839a.firebasestorage.app',
    measurementId: 'G-N51FMJCZE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1HCOjq-vGL1lzhV7bRdIRhcJjBzr9QU',
    appId: '1:330302895133:android:64172d9004a8ea1565c2f4',
    messagingSenderId: '330302895133',
    projectId: 'canteenapp-f839a',
    storageBucket: 'canteenapp-f839a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHv_KCeCXIbjbb0nSdLZoHntLXz7K8Ng',
    appId: '1:330302895133:ios:c75f36b30dc6ae2565c2f4',
    messagingSenderId: '330302895133',
    projectId: 'canteenapp-f839a',
    storageBucket: 'canteenapp-f839a.firebasestorage.app',
    iosBundleId: 'com.example.canteenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIHv_KCeCXIbjbb0nSdLZoHntLXz7K8Ng',
    appId: '1:330302895133:ios:c75f36b30dc6ae2565c2f4',
    messagingSenderId: '330302895133',
    projectId: 'canteenapp-f839a',
    storageBucket: 'canteenapp-f839a.firebasestorage.app',
    iosBundleId: 'com.example.canteenapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbeVl5JtWs3xNAKN5JOKHe-lGbThjL3RA',
    appId: '1:330302895133:web:187287480d8d912865c2f4',
    messagingSenderId: '330302895133',
    projectId: 'canteenapp-f839a',
    authDomain: 'canteenapp-f839a.firebaseapp.com',
    storageBucket: 'canteenapp-f839a.firebasestorage.app',
    measurementId: 'G-HY193LWKSM',
  );
}
